LINUX_CONTAINER_CLOUD_MANAGER = 'SHIPYARD'
HYPERVISOR_CLOUD_MANAGER = 'OPEN_NEBULA'
SHIPYARD_GET_HOST_LIST_REQUEST = '/api/nodes'
SHIPYARD_POST_CONTAINERS_REQUEST = '/api/containers?pull=true'
SHIPYARD_GET_CONTAINERS_REQUEST = '/api/containers'
SHIPYARD_DELETE_CONTAINER_REQUEST = '/api/containers/'
META_TAG = 'meta'
CLOUD_SIM_FILE = './conf/cloudsim.conf'
SIMULATION_CONF_DIR = './conf/simulations/'

ADMN_CNTRL_NO_CAPACITY = 'NO_CAPACITY'
ADMN_CNTRL_SCHEDULED = 'SCHEDULED'
ADMN_CNTRL_INCORRECT_CONFIG = 'INCORRECT_CONFIG'

SIMULATION_STATE_INACTIVE = 'INACTIVE'
SIMULATION_STATE_ACTIVE = 'ACTIVE'
SIMULATION_STATE_RUNNING = 'RUNNING'
SIMULATION_STATE_FINISHED = 'FINISHED'
SIMULATION_STATE_FAILED = 'FAILED'
SIMULATION_STATE_SCHEDULED = 'SCHEDULED'
SIMULATION_STATE_WAITING = 'WAITING'

CONTAINER_STATE_STOPPED = 'stopped'

CONTAINER_NAME_SPLITTER = '-'

CONTAINER_CPU_SHARE_MULTIPLIER = 1024
HOST_OVERBOOKING_RATIO = 1
